//code is super barebones atm. Just placeholders until DB is ready
//Try connection mongo to 35.24.106.170/DarkSoulsData. If we run this localhost just do localhost/DarkSoulsData.
const Discord = require('discord.js');
const Client = new Discord.Client();
var db = [
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Parrying Dagger","Location":"Sold by Unbreakable Patches"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Harpe","Location":"Dropped by the red-eyed enemies at Undead Settlement"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Dagger","Location":"Sold by the Shrine Handmaid/ Dropped by undeads in High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Brigand Twindaggers","Location":"Looted at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Scholar's Candlestick","Location":"Drops from Wax Scholars at Grand Archives"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Bandit's Knife","Location":"Starting equipment: Thief; Sold by Shrine Handmaid after giving Greirat's Ashes; Sold by Greirat of the Undead Settlement"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Handmaid's Dagger","Location":"Drops from Handmaids in the Profaned Capital"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Mail Breaker","Location":"Sorcerer starting weapon; Looted at High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Corvian Greatknife","Location":"Dropped by dagger-wieldind Corvians at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Tailbone Short Sword","Location":"Dropped by enemies at Irythyll Dungeon"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Rotten Ghru Dagger","Location":"Dropped by Ghru at Farron Keep"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Murky Hand Scythe","Location":"Found on a corpse in The Dreg Heap"},
{"Category":"Weapon","SubCategory":"Daggers","ObjectName":"Aquamarine Dagger","Location":"From The Dreg Heap bonfire, drop down and head across the bridge and left up the stairs."},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Long Sword","Location":"Knight starting equipment.; Dropped by hollows at High Wall of Lothric; Sold by Greirat"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Sunlight Straight Sword","Location":"Dropped by Mimic at Lothric Castle"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Broken Straight Sword","Location":"Looted at Cemetery of Ash "},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Broadsword","Location":"Looted at High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Astora Straight Sword","Location":"Looted at High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Lothric Knight Sword","Location":"Sold by Greirat; Dropped by Lothric Knights"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Irithyll Straight Sword","Location":"Dropped by Outrider Knight at Undead Settlement"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Shortsword","Location":"Sold by Shrine Handmaid"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Cleric's Candlestick","Location":"Soul Transposition using Soul of the Deacons of the Deep"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Barbed Straight Sword","Location":"Dropped by Longfinger Kirk at Cathedral of the Deep"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Dark Sword","Location":"Dropped by Darkwraiths"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Gotthard Twinswords","Location":"Looted at Grand Archives"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Lothric's Holy Sword","Location":"Soul Transposition using Soul of the Twin Princes"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Anri's Straight Sword","Location":"Completing Anri of Astora's questline, or just killing him/her."},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Morion Blade","Location":"Give Orbeck's Ashes to Yuria of Londor"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Valorheart","Location":"Ashes of Ariandel DLC: Defeat Champion's Gravetender \u0026 Gravetender Greatwolf"},
{"Category":"Weapon","SubCategory":"Straight Swords","ObjectName":"Ringed Knight Straight Sword","Location":"From the Ringed City Streets bonfire, head out into the swamp and head straight, past several Locust Men, on a corpse."},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Claymore","Location":"In High Wall of Lothric. Beneath the living dragon. Dropped by enemies wielding it in Irithyll"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Bastard Sword","Location":"Sold by Greirat of the Undead Settlement"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Hollowslayer Greatsword","Location":"Soul Transposition using Soul of Rotted Greatwood for 1,000 Souls"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Executioner's Greatsword","Location":"Looted at Cathedral of the Deep"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Black Knight Sword","Location":"Looted at Smoldering Lake"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Flamberge","Location":" Dropped by the thieves wielding the sword at Undead Settlement"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Wolf Knight's Greatsword","Location":"Soul Transposition using Soul of the Blood of the Wolf"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Wolnir's Holy Sword","Location":"Soul Transposition using Soul of High Lord Wolnir"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Greatsword of Judgement","Location":"Soul Transposition using  Soul of Pontiff Sulyvahn"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Moonlight Greatsword","Location":"Soul Transposition using Soul of Consumed Oceiros"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Storm Ruler","Location":"Found in the boss room for Yhorm the Giant/ Completing Siegward of Catarina's questline"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Firelink Greatsword","Location":"Soul Transposition using Soul of the Lords"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Twin Princes' Greatsword","Location":"Trading Lothric's Holy Sword and Lorian's Greatsword at Ludleth of Courland"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Drakeblood Greatsword","Location":"Dropped by knight NPC in Archdragon Peak"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Onyx Blade","Location":"Ashes of Ariandel DLC: Dropped by Sir Vilhelm"},
{"Category":"Weapon","SubCategory":"Greatswords","ObjectName":"Gael's Greatsword","Location":"Obtained via Soul Transposition from the Soul of Slave Knight Gael"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Zweihander","Location":"Sold by Greirat of the Undead Settlement for 6000 souls."},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Greatsword","Location":"Farron Keep, on one of the broken bridges."},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Farron Greatsword","Location":"Soul Transposition using Soul of the Blood of the Wolf"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Fume Ultra Greatsword","Location":"In Smouldering Lake: Drop from Knight Slayer Tsorig"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Profaned Greatsword","Location":"Soul Transposition using Soul of Pontiff Sulyvahn"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Black Knight Greatsword","Location":"Dropped by Black Knights wielding this weapon"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Cathedral Knight Greatsword","Location":"Dropped by Cathedral Knights"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Lorian's Greatsword","Location":"Soul Transposition using Soul of the Twin Princes"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Lothric Knight Greatsword","Location":"Dropped from Lothric Knights wielding this weapon.; Can be purchased from Greirat of the Undead Settlement or Shrine Handmaid if you give her Greirat's Ashes"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Astora Greatsword","Location":"Looted from a corpse at the graveyard near the Cleansing Chapel at Cathedral of the Deep"},
{"Category":"Weapon","SubCategory":"Ultra Greatswords","ObjectName":"Ringed Knight Paired Greatswords","Location":"Drops from Ringed Knight carrying them just before the cathedral, right near the altar where you rank up the Spears of the Church."},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Darkdrift","Location":"Dropped by Yuria of Londor at Firelink Shrine"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Washing Pole","Location":"Sold by the Shrine Handmaid after giving her the Easterner's Ashes for 7,500 souls"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Uchigatana","Location":"Dropped by Sword Master Saber just outside Firelink Shrine"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Chaos Blade","Location":"Outside of the Untended Graves, Firelink Shrine"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Black Blade","Location":"Looted from a Mimic  near the Flame Demon on the way to Smouldering Lake"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Onikiri and Ubadachi","Location":"Dropped by Black Hand Kamui at the top floor the Grand Archives"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Bloodlust","Location":"Rank 1 reward in the Mound-Makers covenant"},
{"Category":"Weapon","SubCategory":"Katanas","ObjectName":"Frayed Blade","Location":"Transposed with Soul of Darkeater Midir"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Scimitar","Location":"Sold by Shrine Handmaid"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Pontiff Knight Curved Sword","Location":"Sold by Greirat/ Dropped by Pontiff Knights at Irythill of the Boral Valley"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Falchion","Location":"Dropped by the Skeletons wielding it at Catacombs of Carthus"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Sellsword Twinblades","Location":"Mercenary starting weapons/ Looted at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Warden Twinblades","Location":" Dropped by Grave Wardens at Cathedral of the Deep and Untended Graves"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Shotel","Location":"Sold by Unbreakable Patches"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Dancer's Enchanted Swords","Location":"Soul Transposition using Soul of the Dancer"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Storm Curved Sword","Location":"Soul Transposition using Soul of the Nameless King"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Carthus Curved Sword","Location":"Dropped by the Skeletons wielding it at Catacombs of Carthus"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Carthus Shotel","Location":" Dropped by Skeletons wielding them at Catacombs of Carthus"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Rotten Ghru Curved Sword","Location":"Dropped by Ghrus at Farron Keep"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Painting Guardian's Curved Sword","Location":" Looted at Anor Londo"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Crescent Moon Sword","Location":" Dropped by Ringfinger Leonhard"},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Follower Sabre","Location":"Ashes of Ariandel DLC: Halfway down the path of roots to the depths of the Painted World."},
{"Category":"Weapon","SubCategory":"Curved Swords","ObjectName":"Demon's Scar","Location":"Obtained via Soul Transposition with the Soul of the Demon Prince"},
{"Category":"Weapon","SubCategory":"Curved Greatswords","ObjectName":"Murakumo","Location":"Dropped by Alva, Seeker of the Spurned at the entrance of Irithyll Dungeon"},
{"Category":"Weapon","SubCategory":"Curved Greatswords","ObjectName":"Carthus Curved Greatsword","Location":"Dropped by Skeletons wielding it at Catacombs of Carthus"},
{"Category":"Weapon","SubCategory":"Curved Greatswords","ObjectName":"Exile Greatsword","Location":"Dropped by Exiled Warriors at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Curved Greatswords","ObjectName":"Old Wolf Curved Sword","Location":"Rank 1 of Watchdogs of Farron"},
{"Category":"Weapon","SubCategory":"Curved Greatswords","ObjectName":"Harald Curved Greatsword","Location":"The Ringed City, On the left end of the swamp after the Earthen Peak bonfire, past the flying hollow."},
{"Category":"Weapon","SubCategory":"Thrusting Swords","ObjectName":"Estoc","Location":"Starting equipment for the Assassin; Sold by Greirat  after his first looting trip"},
{"Category":"Weapon","SubCategory":"Thrusting Swords","ObjectName":"Rapier","Location":"Looted from some remains in the High Wall of Lothric, by the left-side wall of the area where you fight the Winged Knight"},
{"Category":"Weapon","SubCategory":"Thrusting Swords","ObjectName":"Crystal Sage's Rapier","Location":"Soul Transposition using Soul of a Crystal Sage"},
{"Category":"Weapon","SubCategory":"Thrusting Swords","ObjectName":"Irithyll Rapier","Location":"Dropped by Outride Knight in Lothric Castle"},
{"Category":"Weapon","SubCategory":"Thrusting Swords","ObjectName":"Ricard's Rapier","Location":"Dropped from a hostile NPC in Archdragon Peak"},
{"Category":"Weapon","SubCategory":"Thrusting Swords","ObjectName":"Crow Quills","Location":"Ashes of Ariandel DLC: Mound in the center of pool, must be leapt to from a house ledge."},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Battle Axe","Location":"Northen Warrior starting weapon/Looted from a mimic at High Wall of Lothric(Deep Infused)."},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Hand Axe","Location":"Pyromancer starting weapon/ Looted at Undead Settlement"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Thrall Axe","Location":"Dropped from Thralls"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Dragonslayer's Axe","Location":"Dropped by Creighton the Wanderer"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Butcher Knife","Location":"Dropped by enemy wielding it at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Brigand Axe","Location":"Looted at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Winged Knight Twinaxes","Location":"Dropped by Golden Winged Knights"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Eleonora","Location":"Dropped by hand-like enemy at Profaned Capital"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Man Serpent Hatchet","Location":"Dropped by Man Serpents"},
{"Category":"Weapon","SubCategory":"Axes","ObjectName":"Millwood Battle Axe","Location":"Ashes of Ariandel DLC: Looted from a corpse in the tower."},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Greataxe","Location":"Watchdog of Farron covenant builiding roof/drop from axe hollow"},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Demon's Greataxe","Location":"Transpose Soul of a Demon"},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Great Machete ","Location":"Drops by the Saw/Pot wielding enemies at Undead Settlement and Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Yhorm's Great Machete","Location":"Transpose Soul of Yhorm the Giant"},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Dragonslayer Greataxe","Location":"Transpose Soul of Dragonslayer Armour"},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Black Knight Greataxe","Location":"Dropped by Black Knights wielding the weapon"},
{"Category":"Weapon","SubCategory":"Greataxes","ObjectName":"Earth Seeker","Location":"Ashes of Ariandel DLC: Bottom of ravine in snowy mountain area"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Mace","Location":"Cleric starting weapon/ Sold by Greirat"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Club","Location":"Deprived starting weapon/ Dropped by hollows and also looted at High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Morning Star","Location":"Sold by Shrine Handmaid after you give her the Paladin Ashes"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Reinforced Club","Location":"Looted at Undead Settlement"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Drang Hammers","Location":"Looted at Cathedral of the Deep"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Heysel Pick","Location":"Dropped by Yellowfiger Heysel at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Blacksmith Hammer","Location":"Looted at Untended Graves"},
{"Category":"Weapon","SubCategory":"Hammers","ObjectName":"Warpick","Location":"Sold by Greirat after he returns from his first quest"},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Large Club","Location":"Looted from a corpse near the place you and Siegward of Catarina defeated the Fire Demon in Undead Settlement."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Gargoyle Flame Hammer","Location":"Dropped by Rock Gargoyles using this weapon in Profaned Capital or Grand Archives."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Great Club","Location":"Drops from Watchdog of Farron NPC outside Farron Keep."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Vordt's Great Hammer","Location":"Transposed from Soul of Boreal Valley Vordt."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Great Mace","Location":"Dropped from Cathedral Knights wielding this weapon."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Morne's Great Hammer","Location":"Dropped by Eygon of Carim if killed."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Great Wooden Hammer","Location":"Dropped by Villagers at the Undead Settlement wielding this item"},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Smough's Great Hammer","Location":"Found in a chest in Irithyll of the Boreal Valley in the building with the paintings and Silver Knights, on the second floor."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Old King's Great Hammer","Location":"Created with the Soul of the Old Demon King"},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Pickaxe","Location":"Located on a corpse in Irithyll Dungeon (near the giant)."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Dragon Tooth","Location":"Dropped by Havel in Archdragon Peak"},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Spiked Mace","Location":"Dropped by Evangelists at Undead Settlement"},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Quakestone Hammer","Location":"Ashes of Ariandel DLC: Snowy Mountain, at the top of a pass, guarded by a red eyed Millwood Knight."},
{"Category":"Weapon","SubCategory":"Great Hammers","ObjectName":"Ledo's Great Hammer","Location":"Dropped by Silver Knight Ledo when he invades you in The Ringed City (Location)"},
{"Category":"Weapon","SubCategory":"Fist \u0026 Claws","ObjectName":"Caestus","Location":"Looted from a corpse in the sewers of Undead Settlement, right before the Giant Undead Rat."},
{"Category":"Weapon","SubCategory":"Fist \u0026 Claws","ObjectName":"Demon's Fist","Location":"Transposable from Soul of a Demon."},
{"Category":"Weapon","SubCategory":"Fist \u0026 Claws","ObjectName":"Dark Hand","Location":"Sold by Yuria of Londor for 12,000 souls."},
{"Category":"Weapon","SubCategory":"Fist \u0026 Claws","ObjectName":"Claw","Location":"Picked up from beneath the central platform patrolled by Dark Masses in Consumed King's Garden"},
{"Category":"Weapon","SubCategory":"Fist \u0026 Claws","ObjectName":"Manikin Claws","Location":"Dropped by Dark Spirit of Londor that invades you in Irithyll of The Boreal Valley right after the Silver Knights room"},
{"Category":"Weapon","SubCategory":"Fist \u0026 Claws","ObjectName":"Crow Talons","Location":"Ashes of Ariandel DLC: Rooftop in the Corvian Settlement"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Spear","Location":"Starting equipment for the Herald class.; Sold by Greirat at Firelink Shrine"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Tailbone Spear","Location":"Drops from Wretches in Irithyll Dungeon that wield this weapon."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Winged Spear","Location":"Unbreakable Patches: 1500 souls"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Drang Twinspears","Location":"Found at Irithyll of the Boreal Valley."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Arstor's Spear","Location":"Soul Transposition from Soul of the Rotted Greatwood for 1,000 souls."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Four-Pronged Plow","Location":"Dropped by undead wielding this weapon in Undead Settlement"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Saint Bident","Location":"Found at Cathedral of the Deep: next to one of the chained-Giants, there is a big blue door that leads to the area where this if found."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Rotten Ghru Spear","Location":"Dropped by Ghru Grunts wielding this weapon in the swamp area in Farron Keep and in the labyrinth area of Smouldering Lake."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Partizan","Location":"Looted from a hanging corpse near where Cornyx is being held, above the Third bonfire at the Undead Settlement."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Yorshka's Spear","Location":"Located in a chest in a dark room not far from the Church of Yorshka bonfire in Irithyll of the Boreal Valley."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Gargoyle Flame Spear","Location":"Dropped by Stone Gargoyles wielding this weapon in the Profaned Capital \u0026 Grand Archives."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Dragonslayer Swordspear","Location":"Soul Transposition of the Soul of the Nameless King."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Dragonslayer Spear","Location":"Looted from a spot in the area after the Nameless King"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Golden Ritual Spear","Location":"Dropped from a Mimic just above Pontiff Sullyvahn bonfire."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Soldering Iron","Location":"Dropped from a Mimic just above Pontiff Sullyvahn bonfire."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Lothric Knight Long Spear","Location":"Dropped from Lothric Knights wielding them between the Vordt of the Boreal Valley and Dancer of the Boreal Valley bossfight rooms."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Greatlance","Location":"Looted off of the dead body after the red eyed Lothric Knight near the Dragon Barracks bonfire (Before the bridge)"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Pike","Location":"Rare drop from the branch-wielding hollows after the Crucifixion Woods bonfire at the Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Follower Javelin","Location":"Ashes of Ariandel DLC: From the Snowfiled bonfire, up the hill to the right guarded by Farron Followers"},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Ringed Knight Spear","Location":"The Ringed City: Down the steps from Shira and to the right before the swamp. On a corpse behind the Ringed Knight."},
{"Category":"Weapon","SubCategory":"Spears \u0026 Pikes","ObjectName":"Lothric War Banner","Location":"A hidden area just shortly after you meet Lapp for the first time in The Dreg Heap"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Halberd","Location":"Sold by the Shrine Handmaid at Firelink Shrine for 1500 souls.; Dropped by Hollow Soldiers with Halberds in High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Lucerne","Location":"Looted from a corpse to the right of the entrance to Emma at her church in High Wall of Lothric."},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Winged Knight Halberd","Location":"Dropped by Winged Knights wielding this weapon (rare drop)"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Red Hilted Halberd","Location":"In the sewers of Undead Settlement, next to where you find the statue of Velka."},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Black Knight Glaive","Location":"Found in the boss arena for Champion Gundyr"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Gundyr's Halberd","Location":"Craft via Soul Transposition from Soul of Champion Gundyr"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Immolation Tinder","Location":"Drops from Fire Witches in Irithyll of the Boreal Valley."},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Crescent Axe","Location":"Purchased from Shrine Handmaid after giving her Paladin's Ashes."},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Glaive","Location":"Buy for 3500 souls from Greirat"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Splitleaf Greatsword","Location":"Can be bought from the Stone-humped Hag at The Dreg Heap"},
{"Category":"Weapon","SubCategory":"Halberds","ObjectName":"Crucifix of the Mad King","Location":"Drops from Shira when you face her in the final area of The Ringed City"},
{"Category":"Weapon","SubCategory":"Reapers","ObjectName":"Great Scythe","Location":"Looted from Undead Settlement in a destroyed building near the rain of giant arrows and the White Birch Tree."},
{"Category":"Weapon","SubCategory":"Reapers","ObjectName":"Pontiff Knight Great Scythe","Location":"Dropped by the Pontiff Knight wielding this weapon in front of the Pontiff Sulyvahn boss room."},
{"Category":"Weapon","SubCategory":"Reapers","ObjectName":"Great Corvian Scythe","Location":"Dropped by Corvian enemies wielding it in Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Reapers","ObjectName":"Friede's Great Scythe","Location":"Obtained from the Soul of Sister Friede by using Soul Transposition"},
{"Category":"Weapon","SubCategory":"Whips","ObjectName":"Whip","Location":"Looted from a corpse in the Undead Settlement."},
{"Category":"Weapon","SubCategory":"Whips","ObjectName":"Notched Whip","Location":"Beginning of the Cathedral of the Deep. First bonfire."},
{"Category":"Weapon","SubCategory":"Whips","ObjectName":"Witch's Locks","Location":"In a chest in dark room in Floor 1 of Grand Archives. Pull the lever."},
{"Category":"Weapon","SubCategory":"Whips","ObjectName":"Spotted Whip","Location":"Located where you first found Cornyx in Undead Settlement after summoning White Phantom Great Swamp Cuculus and defeating Old Demon King"},
{"Category":"Weapon","SubCategory":"Whips","ObjectName":"Rose of Ariandel","Location":"Ashes of Ariandel DLC: Soul Transposition of Soul of Sister Friede"},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"Short Bow","Location":"Starting Equipment: Thief; Buy: Merchant Greirat's expanded inventory"},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"Longbow","Location":"High Wall of Lothric"},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"Black Bow of Pharis","Location":"Dropped by mini Cleric Beast-like enemy in Farron Keep. There are 3 around a soul to the left of the second bonfire in this area. One of them drops it"},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"Dragonrider Bow","Location":"Smouldering Lake"},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"Composite Bow","Location":"Bought from the Shrine Handmaid for 3,500 souls after giving her the Dreamchaser's Ashes."},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"Darkmoon Longbow","Location":"Soul Transposition using Soul of Aldrich"},
{"Category":"Weapon","SubCategory":"Bows","ObjectName":"White Birch Bow","Location":"The Ringed City - Found on the swamp's cliffside past the Inner Wall area."},
{"Category":"Weapon","SubCategory":"Greatbows","ObjectName":"Dragonslayer Greatbow","Location":"Anor Londo"},
{"Category":"Weapon","SubCategory":"Greatbows","ObjectName":"Onislayer Greatbow","Location":"Profaned Capital"},
{"Category":"Weapon","SubCategory":"Greatbows","ObjectName":"Millwood Greatbow","Location":"Ashes of Ariandel DLC: Up the path near the Millwood Ruins, guarded by wolves and Knights."},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Light Crossbow","Location":"Dropped by the Undeads with Crossbows at the High Wall of Lothric.; Sold by Greirat of the Undead Settlement."},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Knight's Crossbow","Location":"Lothric knight drop"},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Arbalest","Location":"Cathedral of the Deep"},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Sniper Crossbow","Location":"Looted from a corpse at the top of a gatehouse just before the dragons in Lothric Castle"},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Avelyn","Location":"Grand Archives"},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Heavy Crossbow","Location":"Dropped by the crossbow-wielding knight in Cathedral of the Deep"},
{"Category":"Weapon","SubCategory":"Crossbows","ObjectName":"Repeating Crossbow","Location":"Transposed with Soul of Slave Knight Gael"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Sorcerer's Staff","Location":"Shrine Handmaid"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Court Sorcerer's Staff","Location":"Dropped by a mimic located in the Profaned Capital. The mimic is on the second floor of the church looking building that is full of hand beasts."},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Heretic's Staff","Location":"Road of Sacrifices 3rd bonfire, found in the 1st room of the ruins"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Witch Tree Branch","Location":"Looted from corpse behind a locked gate in Irithyll of the Boreal Valley. Must destroy an illusionary railing in order to acquire it."},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Sage's Crystal Staff ","Location":"Dropped by the hostile mage NPC in Grand Archives."},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Izalith Staff","Location":"Smouldering Lake"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Storyteller's Staff","Location":"Dropped by the corvian mage at Road of Sacrifices"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Archdeacon Great Staff","Location":"Reach Rank 2 in Aldrich Faithful Covenant"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Man-Grub's Staff","Location":"Reach rank 2 in Rosaria's Fingers."},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Mendicant's Staff","Location":"Drops from Summoners in Archdragon Peak."},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Preacher's Right Arm","Location":"Swamp in The Ringed City (Location), corpse hanging on structure in the middle"},
{"Category":"Weapon","SubCategory":"Staves","ObjectName":"Murky Longstaff","Location":"The Dreg Heap, past the overgrown Lothric Knights and up the hill into a buidling, on a corpse"},
{"Category":"Weapon","SubCategory":"Flames","ObjectName":"Pyromancy Flame","Location":"Cornyx of the Great Swamp; Starting gear for the Pyromancer Class"},
{"Category":"Weapon","SubCategory":"Flames","ObjectName":"Pyromancer's Parting Flame","Location":"Ashes of Ariandel DLC: At the bottom of the Path of Roots behind the illusory wall."},
{"Category":"Weapon","SubCategory":"Flames","ObjectName":"Demon's Scar","Location":"The Ringed CIty DLC: Transposable from the Soul of the Demon Prince"},
{"Category":"Weapon","SubCategory":"Talismans","ObjectName":"Talisman","Location":"Sold by Shrine Handmaid for 500 souls."},
{"Category":"Weapon","SubCategory":"Talismans","ObjectName":"Saint's Talisman","Location":"Undead Settlement"},
{"Category":"Weapon","SubCategory":"Talismans","ObjectName":"Sunlight Talisman","Location":"Farron Keep, in the swamp near the Estus Soup."},
{"Category":"Weapon","SubCategory":"Talismans","ObjectName":"White Hair Talisman","Location":"Smouldering Lake: Lava pit."},
{"Category":"Weapon","SubCategory":"Talismans","ObjectName":"Sunless Talisman","Location":"Reward for completing the questline of Sirris of the Sunless Realms"},
{"Category":"Weapon","SubCategory":"Talismans","ObjectName":"Canvas Talisman","Location":"Purchased from Shrine Handmaid for 3,000 souls after giving her Paladin's Ashes"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Priest's Chime","Location":"Sold by Greirat for 4000 souls after he is sent scavenging"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Cleric's Sacred Chime","Location":"Dropped by Undead Cleric at Cemetery of Ash"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Caitha's Chime ","Location":"Lothric Castle"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Saint-tree Bellvine","Location":"Looted from a corpse  near the first short cut at Cathedral of the Deep next to the water and the crawling maggot-enemies"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Crystal Chime","Location":"Found in the Grand Archives"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Yorshka's Chime","Location":"Drops from Company Captain Yorshka if killed"},
{"Category":"Weapon","SubCategory":"Sacred Chimes","ObjectName":"Sacred Chime of Filianore","Location":"Given by Shira in The Ringed City when you first speak to her while she is behind the doors"}];


Client.on('ready', ()=>{
	console.log('ready!');
});
	
Client.on('message', (message)=> {
    if (message.content.startsWith('!list')) {
		var query = message.content.replace('!list ','');
		console.log(query);
		var result = null;
		for(var i = 0; i<db.length; i++){
			//var mydb = JSON.stringify(db[i]);
			if(query==db[i].SubCategory){
				message.channel.send(db[i].ObjectName);
			}
			else if(query==db[i].Category){
				message.channel.send(db[i].ObjectName);
			}
		}
		message.channel.send("List Complete!");
	}
   if (message.content.startsWith('!search')) {
		var query = message.content.replace('!search ','');
		for(var i = 0; i<db.length; i++){
			if(query==db[i].ObjectName){
				message.channel.send(db[i].ObjectName+": "+db[i].Location);
			}
		}
	}
});
Client.login('Mzc4NTk1Njc5NzUwMDYyMDgx.DP-dsA.5palAk_mPGrV32Tru1rwAaP12gw');